define({
        all: "全部",
        app: "社區",
        member: "成員",
        removeMember: "移除",
        forbiddenMember: "禁言",
        setAsAdmin: "提升為管理員",
        setAsNormal: "降為普通用戶",
        notificate: "Notificate",
        addMember: "邀請成員",
        movement: "事件",
        setting: "配置",
        remove: "删除",
        school: "學校",
        interest: "興趣",
        join: "加入",
        "public": "公共頁",
        tweets: "動態",
        members: "成員列表",
        activities: "活動",
        photos: "照片",
        file: "檔案",
        blog: "部落格",
        feed: "Feed",
        store: "商店",
        desktop: "桌面",
        add: "創建社區",
        help: "幫助",

        filter: "過濾",
        noFilter: "取消過濾",
        cancelFilter: "全部隐
});