define({
    root: ({
        all: "全部",
        app: "Group",
        member: "成员",
        removeMember: "移除",
        forbiddenMember: "禁言",
        setAsAdmin: "提升为管理员",
        setAsNormal: "降为普通用户",
        notificate: "Notificate",
        addMember: "邀请成员",
        movement: "事件",
        setting: "配置",
        remove: "删除",
        school: "学校",
        interest: "兴趣",
        join: "加入",
        "public": "公共页",
        tweets: "动态",
        members: "成员列表",
        activities: "活动",
        photos: "博客",
        file: "文件",
        blog: "博客",
        feed: "Feed",
        store: "商店",
        desktop: "桌面",
        add: "创建社区",
        help: "帮助",
        prevStep: "前一步",
        skipStep: "跳过",

        filter: "过滤",
        noFilter: "取消过滤",
        cancelFilter: "全部隐藏"
    }),
    "zh": true,
    "zh_tw": true,
    "en": true,
    "ja": true
});
