define({
    all: "all",
    app: "Group",
    member: "member",
    removeMember: "Remove Member",
    forbiddenMember: "Forbidden Member",
    setAsAdmin: "SetAs Admin",
    setAsNormal: "SetAs Normal",
    notificate: "Notificate",
    addMember: "AddMember",
    movement: "Movement",
    setting: "Setting",
    remove: "Remove",
    school: "School",
    interest: "Interest",
    join: "Join",
    "public": "Public",
    tweets: "Tweets",
    members: "Members",
    activities: "Activities",
    photos: "Photos",
    file: "File",
    blog: "Blog",
    feed: "Feed",
    store: "Store",
    desktop: "Desktop",
    add: "Add",
    help: "Help",

    filter: "Filter",
    noFilter: "NoFilter",
    cancelFilter: "CancelFilter"
});